set(PANDORA_SDK_SRCS
    src/Api/PandoraApi.cc
    src/Api/PandoraApiImpl.cc
    src/Api/PandoraContentApi.cc
    src/Api/PandoraContentApiImpl.cc
    src/Geometry/DetectorGap.cc
    src/Geometry/LArTPC.cc
    src/Geometry/SubDetector.cc
    src/Helpers/ClusterFitHelper.cc
    src/Helpers/MCParticleHelper.cc
    src/Helpers/XmlHelper.cc
    src/Managers/AlgorithmManager.cc
    src/Managers/AlgorithmObjectManager.cc
    src/Managers/CaloHitManager.cc
    src/Managers/ClusterManager.cc
    src/Managers/GeometryManager.cc
    src/Managers/InputObjectManager.cc
    src/Managers/MCManager.cc
    src/Managers/Manager.cc
    src/Managers/Metadata.cc
    src/Managers/ParticleFlowObjectManager.cc
    src/Managers/PluginManager.cc
    src/Managers/TrackManager.cc
    src/Managers/VertexManager.cc
    src/Objects/CaloHit.cc
    src/Objects/CartesianVector.cc
    src/Objects/Cluster.cc
    src/Objects/Helix.cc
    src/Objects/Histograms.cc
    src/Objects/MCParticle.cc
    src/Objects/OrderedCaloHitList.cc
    src/Objects/ParticleFlowObject.cc
    src/Objects/Track.cc
    src/Objects/TrackState.cc
    src/Objects/Vertex.cc
    src/Pandora/ExternallyConfiguredAlgorithm.cc
    src/Pandora/ObjectCreation.cc
    src/Pandora/Pandora.cc
    src/Pandora/PandoraImpl.cc
    src/Pandora/PandoraObjectFactories.cc
    src/Pandora/PandoraSettings.cc
    src/Persistency/BinaryFileReader.cc
    src/Persistency/BinaryFileWriter.cc
    src/Persistency/EventReadingAlgorithm.cc
    src/Persistency/EventWritingAlgorithm.cc
    src/Persistency/FileReader.cc
    src/Persistency/FileWriter.cc
    src/Persistency/Persistency.cc
    src/Persistency/XmlFileReader.cc
    src/Persistency/XmlFileWriter.cc
    src/Plugins/EnergyCorrectionsPlugin.cc
    src/Plugins/ParticleIdPlugin.cc
    src/Templates/TemplateAlgorithm.cc
    src/Templates/TemplateAlgorithmTool.cc
    src/Xml/tinystr.cc
    src/Xml/tinyxml.cc
    src/Xml/tinyxmlerror.cc
    src/Xml/tinyxmlparser.cc
)
